common: &common
  pagination_per_page: 20

  # custom session handler
  remote_external_hash: "__external_hash"
  remote_cookies: "__session"

  # false - users cant gain achievements
  gain_achievements: true

  # true - generate more not unique impressions, must include this in badges_config
  # false - not save impressions to database
  unique_impressions: true

  manage_achievements: true
  manage_users: true
  manage_login: true

  gravatar_url: "http://www.gravatar.com/avatar/"

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common
