max_rep_by_up_votes:             200

confirm_email:                   10

day_activity:                     0
day_inactivity:                   0

#
# create, edit, delete, open posts
#
create_thr:                       1
delete_thr:                      -1 # recommend -3

create_an:                        2
delete_an:                       -2

revise:                           0
revert:                           0

flag:                            -2
close_thr:                        1 # not used
reopen_thr:                      -1 # not used
create_comment:                   0

#
# best answers
#
an_resolved:                      2
receives_an_resolved:            15

#
#  vote questions
#
vote_up_thr:                      0
vote_down_thr:                   -1
thr_receives_up_vote:             5 # recommend 10
thr_receives_down_vote:          -2

#
#  vote answers
#
vote_up_an:                       0
vote_down_an:                    -1
an_receives_up_vote:             10
an_receives_down_vote:           -2

vote_up_comment:                  0

vote_down_comment:                0
